### ISSUE TITLE
Parent stacking context not working?

### ISSUE THREAD

**Issue by OliverJAsh** [gwwar/z-context#13]
E.g. https://output.jsbin.com/zovecuzoce/1

```html
<div class="absolute">
    <div class="relative">
        <div class="child">foo</div>
    </div>
</div>
```

```css
.absolute {
    position: absolute;
}

.relative {
    position: relative;
}
```

When selecting `.relative`:

![image](https://user-images.githubusercontent.com/921609/67088537-4cabd580-f19d-11e9-97b6-cd92e41e7955.png)

Expected parent stacking context: `.absolute`

When selecting `.child`:

![image](https://user-images.githubusercontent.com/921609/67088543-503f5c80-f19d-11e9-89ff-5f2e5f77b4ae.png)

Expected parent stacking context: `.relative`
